import {
  LuPencil,
  LuEraser,
  LuPaintBucket,
  LuPipette,
  LuMousePointerClick,
  LuMove,
  LuMinus,
  LuSquare,
  LuCircle,
  LuPlay,
  LuPause,
  LuPlus,
  LuEye,
  LuEyeOff,
  LuLock,
  LuLockOpen,
  LuTrash,
  LuArrowUp,
  LuArrowDown,
  LuFolderOpen,
  LuSave,
  LuUndo,
  LuRedo,
  LuGitBranch,
  LuCheck,
  LuFile,
  LuTriangleAlert,
  LuWand,
  LuFlipHorizontal2,
  LuFlipVertical2,
  LuSkipBack,
  LuSkipForward,
  LuSettings,
  LuX,
  LuRotateCw,
  LuRotateCcw,
  LuRepeat,
  LuRepeat1,
  LuPalette,
  LuMerge,
  LuStepForward,
  LuStepBack,
  LuDownload,
  LuImage,
  LuPackage,
  LuArrowUpDown,
  LuPenLine,
  LuLink,
  LuLayoutDashboard,
  LuHand,
  LuMaximize,
  LuSquareDashedMousePointer,
} from 'react-icons/lu';

export const IconRegistry = {
  // Tools - Drawing
  ToolPencil: LuPencil,
  ToolEraser: LuEraser,
  ToolFill: LuPaintBucket,
  ToolPicker: LuPipette,
  ToolLine: LuMinus,
  ToolRectangle: LuSquare,
  ToolEllipse: LuCircle,

  // Tools - Selection
  ToolSelect: LuMousePointerClick,
  ToolMagicWand: LuWand,

  // Tools - Transform
  ToolMove: LuMove,
  ToolFlipHorizontal: LuFlipHorizontal2,
  ToolFlipVertical: LuFlipVertical2,
  ToolPan: LuHand,
  ToolScale: LuMaximize,
  ToolRotate: LuRotateCw,
  ToolTransform: LuSquareDashedMousePointer,

  // Playback / Timeline
  Play: LuPlay,
  Pause: LuPause,
  SkipBack: LuSkipBack,
  SkipForward: LuSkipForward,
  Add: LuPlus,

  // Layers / Options
  VisibleOn: LuEye,
  VisibleOff: LuEyeOff,
  LockOn: LuLock,
  LockOff: LuLockOpen,
  Delete: LuTrash,
  ArrowUp: LuArrowUp,
  ArrowDown: LuArrowDown,
  
  // Generic
  Folder: LuFolderOpen,
  FolderOpen: LuFolderOpen,
  Save: LuSave,
  Undo: LuUndo,
  Redo: LuRedo,
  GitBranch: LuGitBranch,
  GitCommit: LuCheck,
  Alert: LuTriangleAlert,
  File: LuFile,
  Settings: LuSettings,
  Close: LuX,
  RotateCw: LuRotateCw,
  RotateCcw: LuRotateCcw,
  Repeat: LuRepeat,
  RepeatOne: LuRepeat1,
  Palette: LuPalette,
  Merge: LuMerge,
  StepForward: LuStepForward,
  StepBack: LuStepBack,
  Download: LuDownload,
  Image: LuImage,
  Package: LuPackage,
  SwapColors: LuArrowUpDown,
  Edit: LuPenLine,
  Link: LuLink,
  Layout: LuLayoutDashboard,
};
